# Generated by Django 2.2.4 on 2020-06-23 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='proj_employee',
        ),
    ]
